### ISSUE TITLE
Top part of the result including particle text is hidden on smaller screen by header bar

### ISSUE THREAD

**Issue by yocjyet** [borh-lab/natsume-simple#3]
<img width="825" alt="Screenshot 2024-11-26 at 16 27 29" src="https://github.com/user-attachments/assets/29adaa00-3894-4c07-bcac-ac51fe668bcd">

**Comment by borh** [comment]
In general, the header bar should never overflow to two lines but stay static at one. We can hide some of the elements or make them more compact.

**Comment by borh** [comment]
Fixed with 9e71944bfda3ea8993bf515704b1f262564a7706
